CREATE DATABASE ESCOLA; 
USE ESCOLA;            

CREATE TABLE ALUNO (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOME VARCHAR(255) NOT NULL,        
    MATRICULA INT NOT NULL UNIQUE,     
    EMAIL VARCHAR(255),                
    ENDERECO VARCHAR(255),             
    TELEFONE VARCHAR(15)               
);

CREATE TABLE LIVRO (
    COD_LIVRO INT AUTO_INCREMENT PRIMARY KEY, 
    TITULO VARCHAR(255) NOT NULL,             
    AUTOR VARCHAR(255),                       
    COD_SESSAO INT,                           
    FOREIGN KEY (COD_SESSAO) REFERENCES SESSAO(CODIGO)
);

CREATE TABLE SESSAO (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY, 
    DESCRICAO VARCHAR(255),               
    LOCALIZACAO VARCHAR(255)              
);

CREATE TABLE EMPRESTIMO (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY, 
    DATA_HORA DATETIME NOT NULL,           
    MATRIC_ALUNO INT NOT NULL,             
    DATA_DEVOLUCAO DATE,                   
    FOREIGN KEY (MATRIC_ALUNO) REFERENCES ALUNO(MATRICULA) 
);

CREATE TABLE LIVRO_EMPRESTIMO (
    COD_LIVRO INT NOT NULL,                  
    COD_EMPRESTIMO INT NOT NULL,             
    PRIMARY KEY (COD_LIVRO, COD_EMPRESTIMO), 
    FOREIGN KEY (COD_LIVRO) REFERENCES LIVRO(COD_LIVRO),     
    FOREIGN KEY (COD_EMPRESTIMO) REFERENCES EMPRESTIMO(CODIGO) 
);
